### ISSUE TITLE
リソース（URL）設計

### ISSUE THREAD

**Issue by shirotamaki** [shirotamaki/outdoor-heart-sutra#20]
## プラクティス概要
- https://bootcamp.fjord.jp/practices/229

## 参考
- https://bootcamp.fjord.jp/pages/79

**Comment by shirotamaki** [comment]
# リソース設計

|Method|Path|Description|
|----|----|----|
|GET|/welcome|ログイン前のトップページ|
|GET|/|ログイン後のトップページ|
|DELETE|/logout|ログアウト|
|DELETE|/me|アカウント削除|
|GET|/sutras/:sutra_id/new|撮影モード|
|POST|/sutras/:sutra_id/photos|写真を保存する|
|GET|/sutras/:sutra_id|詳細モード（写真、位置情報、メモ）|
|POST|sutras/:sutra_id/memos|メモを追加する|
|PATCH|sutras/:sutra_id/momos|メモを編集する|
|DELETE|sutras/:sutra_id|削除する（写真、位置情報、メモ）|

**Comment by yoshitsugu** [comment]
- userとsutraの組み合わせに対してphotoとmemoは1つだけつく理解であっていますか？(「空」なら「空」用のphotoとmemoが1つずつつくイメージ) photoがメインなサービスなように思えたので、pathとしても photoに対する操作だけやればいいのかなと思いました。photoだけ削除してmemoが残るパターンがもしあるならそうでもないかもですが。
- フロントがNextjsなら  `/sutras/:sutra_id/photos/new` はNextjs上のpathになりますかね？フロントとバックエンドでそれぞれリソース設計したほうがよいかもですね。

**Comment by shirotamaki** [comment]
@yoshitsugu 

> userとsutraの組み合わせに対してphotoとmemoは1つだけつく理解であっていますか？

はい！合っています。

> photoだけ削除してmemoが残るパターンがもしあるならそうでもないかもですが。

photoだけ削除してmemoが残るパターンはないため修正しました。

フロントエンドとバックエンドで分けて設計し直しました。

ご確認お願いします🙏

**Comment by yoshitsugu** [comment]
- sutraとログインユーザーがわかれば `photo_id` は特定できるので少なくともフロント側の写真詳細ページとかは `/sutras/:sutra_id/` でも十分かなという気がしました。
- sutra自体のRESTに見えるから微妙、ということであれば `/sutra_photos/:sutra_id` とかでもいいのかもです。
- エラー画面はリダイレクトしてもいいですが、URLは同じでエラー表示ポップアップみたいなのをだすだけでもいいのかなと思います。

**Comment by shirotamaki** [comment]
@yoshitsugu 

> sutraとログインユーザーがわかれば photo_id は特定できるので少なくともフロント側の写真詳細ページとかは /sutras/:sutra_id/ でも十分かなという気がしました。

修正しました。

> エラー画面はリダイレクトしてもいいですが、URLは同じでエラー表示ポップアップみたいなのをだすだけでもいいのかなと思います。

ペーパープロトタイプ提出時にUIについて町田さんよりレビュー頂いた際、「エラーページは個別で用意した方がいい」とのことでしたので、今回はエラー画面へリダイレクト方式でいきたいと思います。

ご確認お願いします🙏

**Comment by yoshitsugu** [comment]
OKです〜

**Comment by shirotamaki** [comment]
## 最終変更後のリソース設計
### フロントエンド

|Method|Path|Description|
|----|----|----|
|- |/|ログイン前のトップページ（サービス紹介ページ）|
|- |/|ログイン後のトップページ|
|- | /sutras/:sutra_id | photo登録|
|- | /sutras/:sutra_id | photo編集|
|- | /sutras/:sutra_id | note登録、編集|
|- | /maps| 全体地図|
|- | /about|  サービス内容の説明|
|- | /mypage| マイページ|
|- | /delete-account |アカウント削除|
|- | /terms_of_service | 利用規約|
|- | /privacy_policy | プライバシーポリシー|
|- | /error | エラー画面|

### バックエンド

|Method|Path|Controller#Action|Description| 
|----|----|----|----|
|GET|/api/v1/users/find(.:format)  | api/v1/users#find_user| Emailアドレスからuserを検索し取得する |
|POST|/api/v1/users(.:format) | api/v1/users#create |userを作成する|
|GET  |/api/v1/users/:id(.:format) | api/v1/users#show|user_idからuserを検索し取得する  |
|DELETE | /api/v1/users/:email(.:format)| api/v1/users#destroy {:email=>/[^\/]+/}| userを削除する|
| GET | /api/v1/sutras(.:format)| api/v1/sutras#index| sutraの一覧を取得する |
| GET |/api/v1/sutras/:id(.:format)  |  api/v1/sutras#show |sutra_idからsutraを取得する |
| GET |/api/v1/photos/find(.:format)  |  api/v1/photos#find_photo_by_sutra_and_user |sutra_id と user_id からphotoを検索し取得する   |
| GET | /api/v1/users/:user_id/photos(.:format) | api/v1/photos#index_by_user| user_id から user を検索しuserが所有するphotoを全て取得する|
| POST | 	/api/v1/photos(.:format)  |   api/v1/photos#create |photoを作成する |
| GET | /api/v1/photos/:id(.:format)	  | api/v1/photos#show | photo_id からphotoを検索し取得する |
| PATCH | /api/v1/photos/:id(.:format) | api/v1/photos#update | photoを更新する  |
| DELETE  | /api/v1/photos/:id(.:format) | api/v1/photos#destroy | photoを削除する |

### DB設計
```rb
# backend/db/schema.rb

ActiveRecord::Schema[7.0].define(version: 2023_06_07_011135) do
  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "active_storage_attachments", force: :cascade do |t|
    t.string "name", null: false
    t.string "record_type", null: false
    t.bigint "record_id", null: false
    t.bigint "blob_id", null: false
    t.datetime "created_at", null: false
    t.index ["blob_id"], name: "index_active_storage_attachments_on_blob_id"
    t.index ["record_type", "record_id", "name", "blob_id"], name: "index_active_storage_attachments_uniqueness", unique: true
  end

  create_table "active_storage_blobs", force: :cascade do |t|
    t.string "key", null: false
    t.string "filename", null: false
    t.string "content_type"
    t.text "metadata"
    t.string "service_name", null: false
    t.bigint "byte_size", null: false
    t.string "checksum"
    t.datetime "created_at", null: false
    t.index ["key"], name: "index_active_storage_blobs_on_key", unique: true
  end

  create_table "active_storage_variant_records", force: :cascade do |t|
    t.bigint "blob_id", null: false
    t.string "variation_digest", null: false
    t.index ["blob_id", "variation_digest"], name: "index_active_storage_variant_records_uniqueness", unique: true
  end

  create_table "photos", force: :cascade do |t|
    t.string "note", limit: 256
    t.float "latitude"
    t.float "longitude"
    t.string "address"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "user_id", null: false
    t.bigint "sutra_id", null: false
    t.index ["sutra_id"], name: "index_photos_on_sutra_id"
    t.index ["user_id"], name: "index_photos_on_user_id"
  end

  create_table "sutras", force: :cascade do |t|
    t.string "kanji", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "users", force: :cascade do |t|
    t.string "provider", null: false
    t.string "uid", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "name", null: false
    t.string "email", null: false
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["uid"], name: "index_users_on_uid", unique: true
  end

  add_foreign_key "active_storage_attachments", "active_storage_blobs", column: "blob_id"
  add_foreign_key "active_storage_variant_records", "active_storage_blobs", column: "blob_id"
  add_foreign_key "photos", "sutras"
  add_foreign_key "photos", "users"
end
```
