### ISSUE TITLE
DB設計をする

### ISSUE THREAD

**Issue by shirotamaki** [shirotamaki/outdoor-heart-sutra#4]
## プラクティス概要
- https://bootcamp.fjord.jp/practices/229

## 参考
- https://bootcamp.fjord.jp/pages/297
- https://gihyo.jp/magazine/wdpress/archive/2022/vol130

**Comment by shirotamaki** [comment]
## DB設計

![Image](https://user-images.githubusercontent.com/65638955/219949327-67f81eb2-75b2-494c-8169-8bc24fcdc017.png)


### Users テーブル
- Google認証を利用するためproviderとuidを持たせています。

### Sutras テーブル
- 般若心経278文字のデータを持せています。
- 初期設定時にデータを投入し追加、変更、削除はしないデータになります。

### Photos テーブル
- photo_dataは、写真データをバイナリデータとして持たせます。

### Addresses テーブル
- GoogleMaps のWeb APIを利用します。[Geocording API](https://developers.google.com/maps/documentation/geocoding/overview?hl=ja)のジオコーディングを利用しデータを取得します。
  - latitudeは、緯度データです。浮動小数点数型で格納します。
  - longitudeは、経度データです。同上。
  - prefecture以下は住所詳細データです。
  - GPS機能の不備により取得できないことも考慮しNot Null制約にはしていません。

### Memos テーブル
- noteは、メモ情報を格納します。
- メモ入力は任意なのでNot Null制約にはしていません。

**Comment by yoshitsugu** [comment]
- リソース設計のほうに書きましたが、photoがメインなサービスであるように見えるので、それが正しいなら memoもphotoに統合してしまってよいかなと思います。
- `city` や `town` など住所の細かい情報は分ける必要がなければ一つのstringでもいいのかなと思いました。Geocoding APIの制約上わけたほうがよい、とかであれば大丈夫です。

**Comment by shirotamaki** [comment]
@yoshitsugu 
上記修正してみました。
photoがメインのサービスなので、メモと位置情報はPhotosテーブルのカラムへ追加しました。
住所の情報は分けずにひとつにまとめました。➡`formatted_address`

ご確認お願いします🙏

**Comment by yoshitsugu** [comment]
よさそうです :ok_man:
